spring:
  application:  
    name: feign-client 
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
         
  